### ISSUE TITLE
No methods on dbm-num-records

### ISSUE THREAD

**Issue by NSchweers** [kraison/cl-kyoto-cabinet#2]
Am I missing something?  Are there supposed to be methods on this generic function, or is the binding simply incomplete?  Which would be fine, I just want to know if I’m doing something wrong.

EDIT: I’ve been doing a little digging, trying to provide a method myself.  I noticed that according to kyoto-cabinet-ffi.lisp the function kcdbcount takes a pointer and returns a pointer, while the C interace docs say that it returns an int32_t.  

Any ideas?  Note that I don’t know particularly much about CFFI.

**Comment by kraison** [comment]
The generic is there as a place holder;  I haven't needed record counts, so it never got fleshed out.  I just pushed an update with a properly defined method.

**Comment by kraison** [comment]
Let me know if that works for you and I will close this issue.
