### ISSUE TITLE
Memory leak in GET-SOMETHING

### ISSUE THREAD

**Issue by NSchweers** [kraison/cl-kyoto-cabinet#4]
The function GET-SOMETHING allocates memory (FOREIGN-ALLOC and by calling either KCCURGETKEY or KCCURGETVALUE).  This memory is not reclaimed.  The former can be allocated on the stack, the latter has to be released by KCFREE.

As the patch is so simple, I’ll just include the fixed definition here:

```lisp
(defun get-something (iter fn &optional (type :string))
  (with-foreign-object (size :pointer)
    (let ((val (funcall fn (ptr-of iter) size NIL)))
      (unwind-protect
           (convert-to-lisp type val size)
        (kcfree val)))))
```

**Comment by kraison** [comment]
Thanks for the patch. I'll incorporate it once I am back from vacation.
